#!/usr/bin/env node
// POC delivery for the Stavros harness: generate a standalone, parameterized Python
// reproduction script for a verified finding.
//   node tools/gen-poc.js <finding-id|--latest> [--out <file>]
//   node tools/gen-poc.js <finding-id|--latest> --stdout
//
// Convention (from the pentest persona, SeaOf0/dsh-redteam-model MIT):
//   - -u/--target required (never hardcode the real target)
//   - read-only / minimal-impact checks only by default
//   - destructive steps disabled by default behind a flag (--dangerous)
//   - exit code 0 = reproduced
// Output goes to reports/exp/<finding-id>.py by default and is referenced by the report.

'use strict';
const fs = require('fs');
const path = require('path');

const REPORTS = path.join(__dirname, '..', 'reports');
const FINDINGS = path.join(REPORTS, 'findings.jsonl');
const EXP_DIR = path.join(REPORTS, 'exp');

function loadFindings() {
  try {
    return fs.readFileSync(FINDINGS, 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l));
  } catch { return []; }
}

function findingId(f) {
  return (f.id || `${(f.host || 'host').replace(/[^a-zA-Z0-9]/g, '_')}-${(f.title || 'finding').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 24)}`).toLowerCase();
}

function pickFinding(arg) {
  const all = loadFindings();
  if (!all.length) return null;
  if (arg === '--latest') {
    const verified = all.filter((f) => f.status === 'verified' || f.verified);
    return verified.length ? verified[verified.length - 1] : all[all.length - 1];
  }
  return all.find((f) => findingId(f) === arg) || all.find((f) => String(f.id) === arg) || null;
}

function methodOf(f) {
  const poc = String(f.poc || '');
  if (/GET|curl\s+['"]?https?:\/\//i.test(poc)) return 'GET';
  if (/POST|--data|-d\s|--data-raw/i.test(poc)) return 'POST';
  return 'GET';
}

function genPython(f) {
  const id = findingId(f);
  const method = methodOf(f);
  const targetHint = String(f.endpoint || f.host || 'https://target.example/path');
  const title = String(f.title || 'Finding').replace(/"/g, '\\"');
  const pocLine = String(f.poc || '').replace(/"/g, '\\"').replace(/\n/g, '\\n').slice(0, 400);

  return `#!/usr/bin/env python3
# Reproducer for finding "${title}" — generated by tools/gen-poc.js.
# Usage:
#   python3 ${id}.py -u "${targetHint}"
#   python3 ${id}.py -u <target> --dangerous   # enable destructive steps (disabled by default)
# Exit code 0 = reproduced (indicator found), 1 = not reproduced, 2 = usage error.
#
# Read-only / minimal-impact by default: it only sends the requests needed to confirm the
# indicator. NEVER run against a target without authorization.

import argparse
import sys
import urllib.request
import urllib.error

def build_request(base):
    """Construct the reproduction request for this finding (parameterized target)."""
    # Original PoC evidence (structural, scrubbed): ${pocLine}
    url = base.rstrip('/') + '${String(f.endpoint || '').replace(/"/g, '\\"')}'
    req = urllib.request.Request(url, method='${method}')
    req.add_header('User-Agent', 'StavrosReproducer/1.0')
    return req

def check_indicator(body, status):
    """Return True when the vulnerability indicator is present in the response."""
    # Replace this with the concrete indicator from the finding (marker string / status code).
    return status == 200 and len(body) > 0

def main():
    ap = argparse.ArgumentParser(description='Reproduce: ${title}')
    ap.add_argument('-u', '--target', required=True, help='Target base URL (never hardcoded)')
    ap.add_argument('--dangerous', action='store_true',
                    help='Enable destructive steps (default: off — read-only reproduction)')
    args = ap.parse_args()

    if args.dangerous:
        print('DANGEROUS steps are disabled in the generated reproducer by convention.', file=sys.stderr)
        print('If this finding requires a write step, extend the script consciously.', file=sys.stderr)

    req = build_request(args.target)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            body = resp.read().decode('utf-8', errors='replace')
            status = resp.status
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='replace')
        status = e.code

    if check_indicator(body, status):
        print(f'REPRODUCED (HTTP {status})')
        sys.exit(0)
    print(f'NOT reproduced (HTTP {status})')
    sys.exit(1)

if __name__ == '__main__':
    main()
`;
}

function main() {
  const args = process.argv.slice(2);
  const arg = args[0];
  if (!arg || (arg !== '--latest' && arg.startsWith('-'))) {
    console.error('usage: node tools/gen-poc.js <finding-id|--latest> [--stdout|--out <file>]');
    process.exit(2);
  }
  const f = pickFinding(arg);
  if (!f) {
    console.error(`[gen-poc] no finding for "${arg}" in reports/findings.jsonl`);
    process.exit(1);
  }
  const id = findingId(f);
  const py = genPython(f);
  if (args.includes('--stdout')) {
    process.stdout.write(py);
    process.exit(0);
  }
  const out = args.includes('--out')
    ? path.resolve(args[args.indexOf('--out') + 1])
    : path.join(EXP_DIR, `${id}.py`);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, py);
  console.log(`[gen-poc] wrote ${out} for finding "${f.title}"`);
}

if (require.main === module) main();

module.exports = { findingId, pickFinding, genPython, EXP_DIR };